/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 charete_sae.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./charete_sae.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-4.67, 1.135, -0.38]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[-6.631, 0.792, 1.095]} rotation={[0, 0, -Math.PI / 2]} scale={[1.287, 0.953, 1.315]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[-6.644, 0.609, -3.278]} rotation={[0, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[-10.807, 0.792, 1.621]} rotation={[0, 0, -Math.PI / 2]} scale={[1.287, 0.953, 1.315]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} position={[-11.413, 0.609, -2.472]} rotation={[0, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[-4.659, 2.543, -1.28]} rotation={[-1.596, 0, 0]} scale={[0.916, 0.99, 0.699]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[-4.659, 2.543, 1.137]} rotation={[-1.596, 0, 0]} scale={[0.916, 0.99, 0.699]} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[-4.686, 2.668, -0.985]} scale={[1, 0.473, 0.83]} />
    </group>
  )
}

useGLTF.preload('/charete_sae.glb')
